### PR TITLE
fix #76 make GitEvent throw exception when handed bad json.

### LINKED ISSUE #76: GitEvent crashes if JSON is invalid

### PR DESCRIPTION
**Pull request by gpihl**
Fixes #76

This is now caught in the handle function of ContinuousIntegrationServer.java.
Also reenabled the affected test.

### CODE REVIEW

File: src/main/java/CI/ContinuousIntegrationServer.java [hunk 1]
```diff
@@ -62,8 +62,8 @@ public void handle(String target,
                     handler.request_push();
                     response.getWriter().println("CI job done");
                 }
-                catch (IOException ioe) {
-                    ioe.printStackTrace();
+                catch (Exception ex) {
```
Comment (mstniy) [inline src/main/java/CI/ContinuousIntegrationServer.java]: "catch (Exception)" is a bad pattern, as it catches all possible exceptions. A better approach would be to catch only JSONException's here.

Even then, the "catch" would cover too much code. It only needs to cover the line where the GitEvent is created.

**Review by mstniy — APPROVED** [review]
Looks good
